# Generated by Django 4.2. Names the reverse M2M accessor 'players', adds
# deterministic ordering for pagination, a name index and a team uniqueness rule.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ('last_name', 'first_name')},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ('city', 'mascot')},
        ),
        migrations.AlterField(
            model_name='player',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='players', to='sports.team'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['last_name', 'first_name'], name='player_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('city', 'mascot'), name='unique_team_city_mascot'),
        ),
    ]
